#include<stdio.h>

int main()
{
    int n=1;

    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
        printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    printf("%i\n", n);
    n=n+1;
    return 0;
}
